footer
front-end-by-rimantas/20-grupe-portfolio-neuron pull request #48
Opened 2021-01-02 13:16 UTC by Ramazinas

its look all ok, just problem with bacground, maybe will find solution later.

2021-01-03 19:44 UTC, EgleJuske requested changes
no need to wrap `<a>` tags in `<p>`

2021-01-03 19:44 UTC, EgleJuske commented on index.html
> +                                        <br>
better add `margin-top`  than `<br>` tag

2021-01-03 22:29 UTC, InetaVei approved these changes, later dismissed

2021-01-04 07:36 UTC, InetaVei approved these changes

2021-01-04 08:37 UTC, Jjurgita approved these changes

2021-01-04 09:30 UTC, EgleJuske approved these changes

2021-01-04 09:30 UTC, merged