Works section
front-end-by-rimantas/20-grupe-portfolio-neuron pull request #65
Opened 2021-01-05 14:39 UTC by Jjurgita

Work section with responsive design

2021-01-05 14:41 UTC, Jjurgita commented
Unable to add padding for the bottom part. If you have any idea how to do it nicely, please let me know :)

2021-01-05 15:00 UTC, JurateJ commented on css/components/works.css
> +    padding-top: 40px;
margin-bottom: 40px;   may help?

2021-01-05 17:57 UTC, EgleJuske commented on css/components/works.css
> +h2 {
it would be better if you would use `.work h2` selector for header, because now updates header went to the center

2021-01-05 19:48 UTC, Ramazinas approved these changes, later dismissed

2021-01-05 22:34 UTC, belauzas requested changes

2021-01-05 22:34 UTC, belauzas commented on index.html
> +        <div class="second-row">
Tokia CSS klasė neegzistuoja (neaprašyta) -> pakeisti į `row`.

2021-01-05 22:34 UTC, belauzas commented on css/components/works.css
> +    background-size: 100% 100%;
Bėda, jog dėl tokio parašymo vis dar kartais matyti šone spalvota juosta (priklauso nuo ekrano rezoliucijos. Geresenis sprendimas būtų paimti nuotrauką ir pakeisti jos dydį, jog ji būtų kvadratinė (pvz padydinti iki 35x35), tada turint ir šį pseudo elementą kvadartin (26x26) galima panaudoti `background-size: contain;` ir tada nebesimatys mini defektas 🍝

2021-01-06 10:57 UTC, InetaVei approved these changes
nice 👍

2021-01-06 11:08 UTC, EgleJuske approved these changes
looking good 😎

2021-01-06 11:20 UTC, JurateJ approved these changes

2021-01-06 11:55 UTC, belauzas approved these changes
LGTM 🚀

2021-01-06 11:56 UTC, merged