Hero
front-end-by-rimantas/20-grupe-portfolio-neuron pull request #67
Opened 2021-01-05 21:17 UTC by inpasvenskiene

Responsive design
Image animation

2021-01-05 23:06 UTC, belauzas requested changes

2021-01-05 23:06 UTC, belauzas commented on index.html
> +                        <img class="img2 hidden-sm hidden-xs" src="./images/hero/2.png" alt="mechanics-image">
Jei naudojame `grid`, tai tada nenaudojam "bootstrap" klasių, nes nėra prasmės 🤔
Šiuo atveju siūlyčiau tiesiog ištirnti `<div class="main-hero">` elementą.

Kadangi `.right hero` viduje yra 2 nuotraukos ir jos abi turi tas pačias `hidden-sm hidden-xs` klases, tai siūlyčiau jas iškelti ant paties `<div class="right-hero">` elemento - mažiau rašymo ir taip pat veiks 👍

2021-01-06 08:53 UTC, Ramazinas approved these changes, later dismissed
tested, good work

2021-01-06 18:38 UTC, InetaVei approved these changes
i like it :)

2021-01-06 18:55 UTC, Jjurgita approved these changes

2021-01-06 19:21 UTC, belauzas approved these changes

2021-01-06 19:21 UTC, merged