Creativity section
front-end-by-rimantas/20-grupe-portfolio-neuron pull request #68
Opened 2021-01-05 22:37 UTC by InetaVei

changed icons colors and hover. 
I think it looks ok, but it's not perfect yet.

2021-01-05 23:09 UTC, belauzas requested changes
Need some fixing 👍

2021-01-05 23:09 UTC, belauzas commented on css/components/creativity.css
> +#cIcons {
CSS **labai** nerekomenduoju naudoti ID, nes po to bus **labai** sunki tokius selektorius permušti -> keičiam į klasę 👍

2021-01-05 23:09 UTC, belauzas commented on css/components/creativity.css
> +#cIcons:hover {
Same... no ID's -> CSS class 👍

2021-01-06 08:13 UTC, InetaVei commented
changed icons ID to class

2021-01-06 08:15 UTC, belauzas approved these changes

2021-01-06 08:15 UTC, JurateJ approved these changes

2021-01-06 08:15 UTC, Ramazinas approved these changes

2021-01-06 08:15 UTC, Jjurgita approved these changes

2021-01-06 08:15 UTC, EgleJuske approved these changes

2021-01-06 08:15 UTC, merged